"""initial

Revision ID: 0001
Revises:
Create Date: 2026-07-07
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    op.create_table("adr_records",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36)),
        sa.Column("adr_json", sa.Text()),
    )
    op.create_table("api_specs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36)),
        sa.Column("openapi_json", sa.Text()),
        sa.Column("openapi_yaml", sa.Text()),
    )
    op.create_table("architecture_reviews",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36)),
        sa.Column("recommendation_json", sa.Text()),
        sa.Column("needs_review", sa.Boolean()),
    )
    op.create_table("audit_runs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("action", sa.String(100)),
        sa.Column("input", sa.Text()),
        sa.Column("output", sa.Text()),
        sa.Column("status", sa.String(20)),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer()),
    )
    op.create_table("build_projects",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36)),
        sa.Column("name", sa.String(300)),
        sa.Column("description", sa.Text()),
        sa.Column("status", sa.String(30)),
    )
    op.create_table("decisions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36), nullable=True),
        sa.Column("context", sa.Text()),
        sa.Column("problem", sa.Text()),
        sa.Column("decision", sa.Text()),
        sa.Column("alternatives", sa.Text()),
        sa.Column("consequences", sa.Text()),
        sa.Column("status", sa.String(30)),
    )
    op.create_table("diagram_artifacts",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36)),
        sa.Column("diagram_type", sa.String(50)),
        sa.Column("notation", sa.String(20)),
        sa.Column("source_code", sa.Text()),
    )
    op.create_table("documents",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("title", sa.String(500)),
        sa.Column("text", sa.Text()),
        sa.Column("doc_type", sa.String(50)),
        sa.Column("project_name", sa.String(200), nullable=True),
    )
    op.create_table("economic_actuals",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("project_id", sa.String(36)),
        sa.Column("actual_capex", sa.Float()),
        sa.Column("actual_opex_monthly", sa.Float()),
        sa.Column("actual_benefit_monthly", sa.Float()),
        sa.Column("actual_time_saved_hours_monthly", sa.Float()),
        sa.Column("notes", sa.Text()),
    )
    op.create_table("economic_estimates",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("project_id", sa.String(36)),
        sa.Column("rate_backend", sa.Float()),
        sa.Column("rate_frontend", sa.Float()),
        sa.Column("rate_qa", sa.Float()),
        sa.Column("rate_devops", sa.Float()),
        sa.Column("rate_analyst", sa.Float()),
        sa.Column("hosting_cost_monthly", sa.Float()),
        sa.Column("llm_cost_monthly", sa.Float()),
        sa.Column("support_hours_monthly", sa.Float()),
        sa.Column("time_saved_hours_monthly", sa.Float()),
        sa.Column("avg_employee_rate", sa.Float()),
        sa.Column("capex", sa.Float()),
        sa.Column("opex_monthly", sa.Float()),
        sa.Column("benefit_monthly", sa.Float()),
        sa.Column("payback_months", sa.Float()),
        sa.Column("roi_12m_pct", sa.Float()),
    )
    op.create_table("memory_items",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("memory_type", sa.String(50)),
        sa.Column("content", sa.Text()),
        sa.Column("tags", sa.Text()),
        sa.Column("project_name", sa.String(200), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
    )
    op.create_table("project_lessons",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
        sa.Column("project_name", sa.String(200), nullable=True),
        sa.Column("title", sa.String(200)),
        sa.Column("description", sa.Text()),
        sa.Column("category", sa.String(50)),
        sa.Column("impact_type", sa.String(10)),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("document_id", sa.String(36), nullable=True),
        sa.Column("source", sa.String(50)),
    )
    op.create_table("provider_settings",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("updated_at", sa.DateTime()),
        sa.Column("provider", sa.String(50)),
        sa.Column("api_key", sa.Text()),
        sa.Column("model", sa.String(100)),
        sa.Column("base_url", sa.Text()),
        sa.Column("temperature", sa.String(10)),
        sa.Column("max_tokens", sa.String(10)),
        sa.Column("route", sa.String(50)),
        sa.Column("is_active", sa.String(5)),
    )
    op.create_table("qa_runs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("question", sa.Text()),
        sa.Column("answer", sa.Text()),
        sa.Column("sources_json", sa.Text()),
        sa.Column("needs_review", sa.Boolean()),
        sa.Column("error", sa.String(200), nullable=True),
    )
    op.create_table("reviews",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36)),
        sa.Column("review_json", sa.Text()),
        sa.Column("needs_review", sa.Boolean()),
        sa.Column("confidence", sa.String(20)),
        sa.Column("error", sa.String(200), nullable=True),
    )
    op.create_table("risk_catalog",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
        sa.Column("project_name", sa.String(200), nullable=True),
        sa.Column("title", sa.String(200)),
        sa.Column("description", sa.Text()),
        sa.Column("probability", sa.Integer()),
        sa.Column("impact", sa.Integer()),
        sa.Column("category", sa.String(50)),
        sa.Column("status", sa.String(20)),
        sa.Column("owner", sa.String(200), nullable=True),
        sa.Column("mitigation", sa.Text(), nullable=True),
        sa.Column("document_id", sa.String(36), nullable=True),
        sa.Column("source", sa.String(50)),
    )
    op.create_table("snippets",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("document_id", sa.String(36)),
        sa.Column("snippet_text", sa.Text()),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
    )
    op.create_table("task_estimates",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("project_id", sa.String(36)),
        sa.Column("tasks_json", sa.Text()),
        sa.Column("total_hours", sa.Float()),
        sa.Column("confidence", sa.String(20)),
        sa.Column("needs_review", sa.Boolean()),
    )
    op.create_table("users",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
        sa.Column("username", sa.String(100)),
        sa.Column("email", sa.String(200)),
        sa.Column("full_name", sa.String(200)),
        sa.Column("hashed_password", sa.String(256)),
        sa.Column("role", sa.String(20)),
        sa.Column("is_active", sa.Boolean()),
        sa.Column("last_login", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    for table in [
        "adr_records", "api_specs", "architecture_reviews", "audit_runs",
        "build_projects", "decisions", "diagram_artifacts", "documents",
        "economic_actuals", "economic_estimates", "memory_items",
        "project_lessons", "provider_settings", "qa_runs", "reviews",
        "risk_catalog", "snippets", "task_estimates", "users",
    ]:
        op.drop_table(table)
